-- 006_wui_auth.sql
CREATE TABLE wui_utenti (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    creato_il DATETIME DEFAULT CURRENT_TIMESTAMP
);
